import {
    REACT_APP_GET_FILTERS_AR_P01,
    REACT_APP_GET_FILTERS_PY_P01,
    REACT_APP_GET_FILTERS_UY_P01,
    REACT_APP_GET_TABLE_INFO_AR_P01,
    REACT_APP_GET_TABLE_INFO_PY_P01,
    REACT_APP_GET_TABLE_INFO_UY_P01,
    REACT_APP_MEMBER_OF_GROUP_P01,
    REACT_APP_GET_USER_INFO,
    REACT_APP_TZ,
    REACT_APP_CLARO_HOME_URL,
    REACT_APP_PSP_URL,
    REACT_APP_CONTENT_TYPE,
    REACT_APP_CHANNEL_ID,
    REACT_APP_BASE_URL_PROXY,
    REACT_APP_LINE_DATA_PATH,
    REACT_APP_LINE_CHECK_PATH
} from '../config';

// ##### Permisos de Ingreso #####
export const MEMBER_OF_GROUP = REACT_APP_MEMBER_OF_GROUP_P01;

// ##### Endpoints #####
export const ENDPOINTS = {
    // ############### Parametros Usuario ###############
    GET_USER_INFO: REACT_APP_GET_USER_INFO,
    // ##### Url Integration Backend #####
    // #---- sp-data-consumption-service -----
    GET_FILTERS_AR: REACT_APP_GET_FILTERS_AR_P01,
    GET_FILTERS_UY: REACT_APP_GET_FILTERS_UY_P01,
    GET_FILTERS_PY: REACT_APP_GET_FILTERS_PY_P01,
    GET_TABLE_INFO_AR: REACT_APP_GET_TABLE_INFO_AR_P01,
    GET_TABLE_INFO_UY: REACT_APP_GET_TABLE_INFO_UY_P01,
    GET_TABLE_INFO_PY: REACT_APP_GET_TABLE_INFO_PY_P01
};

export const PATH = {
    LINE_DATA: REACT_APP_LINE_DATA_PATH,
    LINE_CHECK: REACT_APP_LINE_CHECK_PATH
}

export const TZ = REACT_APP_TZ;
export const PSP_URL = REACT_APP_PSP_URL;
export const CLARO_HOME_URL = REACT_APP_CLARO_HOME_URL;
export const BASE_URL_PROXY = REACT_APP_BASE_URL_PROXY

export const HEADER = {
    CONTENT_TYPE: REACT_APP_CONTENT_TYPE,
    CHANNEL_ID: REACT_APP_CHANNEL_ID,
}
